server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SumanthRam07/PetService-Config-Repository.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

